In [3]:
import pandas as pd
import re
import numpy as np
indeed = pd.read_csv('/Users/cguy/kelstuff/ga_summer_2016/jobScrape.csv')
indeed

,Unnamed: 0,Company,Job,Location,Salary,Sponsored
0,0,\n LENA Research Foundation,Sr. Research Engineer: Machine Learning and Co...,"Boulder, CO",NaN,True
1,1,"\n\n Alteryx, Inc.","Product Manager, Advanced Analytics","Broomfield, CO",NaN,True
2,2,\n\n CyberCoders,Data Scientist,"Boulder, CO",NaN,True
3,3,\n\n\n Navigant Consulting\n,Research Analyst,"Boulder, CO",NaN,False
4,4,\n\n cliexa\n,Data Scientist Intern,"Boulder, CO",NaN,False
5,5,\n\n\n University of Colorado\n,Professional Research Asst,"Boulder, CO",NaN,False
6,6,"\n\n Somalogic, Inc.\n",Bioinformatics Assoc. II/Sr. Assoc./Analyst/Sc...,"Boulder, CO 80301",NaN,False
7,7,\n\n\n Oracle\n,"Senior Product Manager - Measurement, Oracle D...","Broomfield, CO",NaN,False
8,8,\n\n\n Ibotta\n,Senior Data Scientist,"Denver, CO 80202 (Lodo area)",NaN,False
9,9,\n\n\n University of Colorado\n,Research Associate,"Boulder, CO",NaN,False
10,10,\n\n\n Deloitte\n,Big Data Senior Consultant,"Denver, CO 80203 (Capitol Hill area)",NaN,False
11,11,\n\n\n Deloitte\n,Big Data Manager,"Denver, CO 80203 (Capitol Hill area)",NaN,False
12,12,\n\n\n Planet Pharma\n,Statistical Programmer,"Denver, CO",NaN,False
13,13,\n Specialty Chemicals,Research Scientist,"Denver, CO",NaN,True
14,14,\n Eventus Solutions Group,Junior Data Scientist,"Englewood, CO",NaN,True
15,15,\n Eventus Solutions Group,Junior Data Scientist,"Englewood, CO",NaN,True
16,16,"\n\n Alteryx, Inc.","Product Manager, Advanced Analytics","Broomfield, CO",NaN,True
17,17,\n Specialty Chemicals,Research Scientist,"Denver, CO",NaN,True
18,18,\n\n\n Ball Aerospace\n,Administrative Associate II - National Defense...,"Broomfield, CO",NaN,False
19,19,"\n\n Corgenix, Inc\n",Postdoctoral Fellow - Assay Development,"Broomfield, CO 80020",NaN,False
20,20,\n\n\n UCAR\n,Engineer II,"Broomfield, CO",NaN,False
21,21,\n\n Specialty Chemicals\n,Research Scientist,"Denver, CO",NaN,False
22,22,\n\n\n IMM\n,Software Engineer ? Big Data,"Boulder, CO 80302",NaN,False
23,23,\n\n\n Archer\n,Software Engineer,"Boulder, CO",NaN,False
24,24,\n\n\n Southwest Research Institute\n,SR. RESEARCH SCIENTIST - HELIOPHYSICS,"Boulder, CO",NaN,False
25,25,\n\n\n OnDeck\n,Business Intelligence Analyst,"Denver, CO",NaN,False
26,26,\n\n Stanley Brothers Social Enterprises\n,Research and Development Scientist,"Boulder, CO 80301",NaN,False
27,27,\n\n\n Department Of The Interior\n,"Statistician, GS-1530-12 (DEU-PERM-DS)","Lakewood, CO","[<nobr>$76,341 - $99,243 a year</nobr>]",False
28,28,\n\n CyberCoders,Data Scientist,"Boulder, CO",NaN,True
29,29,\n LENA Research Foundation,Sr. Research Engineer: Machine Learning and Co...,"Boulder, CO",NaN,True
...,...,...,...,...,...,...
1899,1899,"\n\n RetailMeNot, Inc.",Sr. Data Scientist,"Austin, TX",NaN,True
1900,1900,\n Sense Corp,Data Scientist,"Austin, TX",NaN,True
1901,1901,\n\n MaxPoint\n,Senior Data Scientist - Econometrics,"Austin, TX 78759 (Arboretum area)",NaN,False
1902,1902,\n\n\n NVIDIA\n,Research Scientist for Computer Vision / Machi...,"Austin, TX",NaN,False
1903,1903,\n\n\n Alcatel-Lucent\n,Software Developer Co-op,"Austin, TX",NaN,False
1904,1904,\n\n Ocean Conservancy\n,"Conservation Biologist, Gulf Restoration Program","Austin, TX 78701 (Downtown area)",NaN,False
1905,1905,\n\n\n CDK Global\n,Business Security Officer,"Austin, TX",NaN,False
1906,1906,\n\n\n Express Scripts\n,Senior Quantitative UX Researcher,"Austin, TX",NaN,False
1907,1907,\n\n Signature Science\n,Bioinformatics Specialist,"Austin, TX",NaN,False
1908,1908,\n\n The University of Texas System\n,Institutional Research Analyst,"Austin, TX","[<nobr>$4,459 a month</nobr>]",False
1909,1909,\n\n\n Thermo Fisher Scientific\n,Application Scientist,"Austin, TX",NaN,False
1910,1910,\n\n Emoters Robotics\n,Robotics software engineer (involves machine l...,"Austin, TX","[<nobr>$70,000 - $100,000 a year</nobr>]",False
1911,1911,\n\n Indeed,Data Engineer,"Austin, TX",NaN,True
1912,1912,\n\n Main Street Hub,Data Scientist,"Austin, TX",NaN,True
1913,1913,\n\n Indeed,Data Scientist,"Austin, TX",NaN,True
1914,1914,"\n\n RetailMeNot, Inc.",Sr. Data Scientist,"Austin, TX",NaN,True
1915,1915,\n Sense Corp,Data Scientist,"Austin, TX",NaN,True
1916,1916,"\n\n\n Gartner, Inc.\n","Content Marketing Analyst, Gartner Research","Austin, TX",NaN,False
1917,1917,\n\n MaxPoint\n,Senior Data Scientist - Machine Learning,"Austin, TX 78759 (Arboretum area)",NaN,False
1918,1918,\n\n\n The Jag Group\n,Senior Data Scientist - Machine Learning,"Austin, TX 73301 (St Edwards area)",NaN,False
1919,1919,\n\n\n Natera\n,Clinical Data Reporter,"Austin, TX 78731",NaN,False
1920,1920,"\n\n TEL Technology Center, America, Inc.\n",Scientist,"Austin, TX",NaN,False
1921,1921,\n\n Zilliant\n,Senior Software Engineer – Science Team,"Austin, TX 78704 (South Lamar-South Congress a...",NaN,False
1922,1922,\n\n Galvanize\n,"Associate Instructor, Data Scientist","Austin, TX",NaN,False
1923,1923,\n\n\n Indeed\n,Data Scientist,"Austin, TX 78759 (Arboretum area)",NaN,False
1924,1924,\n\n\n University of Texas at Austin\n,Engineering Scientist Associate - GNSS Analyst...,"Austin, TX","[<nobr>$5,400 - $6,500 a month</nobr>]",False
1925,1925,\n\n\n HomeAway\n,Research Data Scientist,"Austin, TX 78704 (South Lamar-South Congress a...",NaN,False
1926,1926,\n\n Indeed,Data Engineer,"Austin, TX",NaN,True
1927,1927,\n\n Main Street Hub,Data Scientist,"Austin, TX",NaN,True
1928,1928,\n\n Indeed,Data Scientist,"Austin, TX",NaN,True

In [4]:
indeed.drop(['Unnamed: 0'], axis=1, inplace=True)

Data Cleaning Plan:

 1) remove '\n'
 
 2) remove white spaces
 
 3) convert types as needed
 
 4) parse job title data
    
    a) senior/manager/lead in job title
    
    b) also, scientist and analyst in job title
 
 5) filter out sponsored
 
 6) fix location
    
    a) keep only city
 
 7) fix salary
 
 8) remove nobr
 
 9) take yearly salaries only
 
    a) DID NOT CONVERT hourly or monthly to annual, instead I discarded. Main rationale: highly probable that the 
    job postings with monthly and hourly rate are part-time jobs
    
    b) get averages for salary range (if a more conservative model is desired, should choose lower end of salary 
    range. if a more competitive model is desired, higher end of salary range should be chosen).
    
    c) get median salary and create a high/low dummy variable column to prep for analysis
    
    d) drop data rows with no salaries
  
  10) Save cleaned dataset as CSV

In [5]:
indeed['Company'].apply(lambda x: str(x))
indeed['Company'].apply(lambda x: type(x))

0       <type 'str'>
1       <type 'str'>
2       <type 'str'>
3       <type 'str'>
4       <type 'str'>
5       <type 'str'>
6       <type 'str'>
7       <type 'str'>
8       <type 'str'>
9       <type 'str'>
10      <type 'str'>
11      <type 'str'>
12      <type 'str'>
13      <type 'str'>
14      <type 'str'>
15      <type 'str'>
16      <type 'str'>
17      <type 'str'>
18      <type 'str'>
19      <type 'str'>
20      <type 'str'>
21      <type 'str'>
22      <type 'str'>
23      <type 'str'>
24      <type 'str'>
25      <type 'str'>
26      <type 'str'>
27      <type 'str'>
28      <type 'str'>
29      <type 'str'>
            ...
1899    <type 'str'>
1900    <type 'str'>
1901    <type 'str'>
1902    <type 'str'>
1903    <type 'str'>
1904    <type 'str'>
1905    <type 'str'>
1906    <type 'str'>
1907    <type 'str'>
1908    <type 'str'>
1909    <type 'str'>
1910    <type 'str'>
1911    <type 'str'>
1912    <type 'str'>
1913    <type 'str'>
1914    <type 'str'>
1915    <type 'str'>
1916    <type 'str'>
1917    <type 'str'>
1918    <type 'str'>
1919    <type 'str'>
1920    <type 'str'>
1921    <type 'str'>
1922    <type 'str'>
1923    <type 'str'>
1924    <type 'str'>
1925    <type 'str'>
1926    <type 'str'>
1927    <type 'str'>
1928    <type 'str'>
Name: Company, dtype: object

In [6]:
index = 0
for comp in indeed['Company']:
    indeed['Company'].iloc[index] = comp.replace("\n", "")
    index += 1
indeed

/Users/cguy/anaconda/lib/python2.7/site-packages/pandas/core/indexing.py:132: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

,Company,Job,Location,Salary,Sponsored
0,LENA Research Foundation,Sr. Research Engineer: Machine Learning and Co...,"Boulder, CO",NaN,True
1,"Alteryx, Inc.","Product Manager, Advanced Analytics","Broomfield, CO",NaN,True
2,CyberCoders,Data Scientist,"Boulder, CO",NaN,True
3,Navigant Consulting,Research Analyst,"Boulder, CO",NaN,False
4,cliexa,Data Scientist Intern,"Boulder, CO",NaN,False
5,University of Colorado,Professional Research Asst,"Boulder, CO",NaN,False
6,"Somalogic, Inc.",Bioinformatics Assoc. II/Sr. Assoc./Analyst/Sc...,"Boulder, CO 80301",NaN,False
7,Oracle,"Senior Product Manager - Measurement, Oracle D...","Broomfield, CO",NaN,False
8,Ibotta,Senior Data Scientist,"Denver, CO 80202 (Lodo area)",NaN,False
9,University of Colorado,Research Associate,"Boulder, CO",NaN,False
10,Deloitte,Big Data Senior Consultant,"Denver, CO 80203 (Capitol Hill area)",NaN,False
11,Deloitte,Big Data Manager,"Denver, CO 80203 (Capitol Hill area)",NaN,False
12,Planet Pharma,Statistical Programmer,"Denver, CO",NaN,False
13,Specialty Chemicals,Research Scientist,"Denver, CO",NaN,True
14,Eventus Solutions Group,Junior Data Scientist,"Englewood, CO",NaN,True
15,Eventus Solutions Group,Junior Data Scientist,"Englewood, CO",NaN,True
16,"Alteryx, Inc.","Product Manager, Advanced Analytics","Broomfield, CO",NaN,True
17,Specialty Chemicals,Research Scientist,"Denver, CO",NaN,True
18,Ball Aerospace,Administrative Associate II - National Defense...,"Broomfield, CO",NaN,False
19,"Corgenix, Inc",Postdoctoral Fellow - Assay Development,"Broomfield, CO 80020",NaN,False
20,UCAR,Engineer II,"Broomfield, CO",NaN,False
21,Specialty Chemicals,Research Scientist,"Denver, CO",NaN,False
22,IMM,Software Engineer ? Big Data,"Boulder, CO 80302",NaN,False
23,Archer,Software Engineer,"Boulder, CO",NaN,False
24,Southwest Research Institute,SR. RESEARCH SCIENTIST - HELIOPHYSICS,"Boulder, CO",NaN,False
25,OnDeck,Business Intelligence Analyst,"Denver, CO",NaN,False
26,Stanley Brothers Social Enterprises,Research and Development Scientist,"Boulder, CO 80301",NaN,False
27,Department Of The Interior,"Statistician, GS-1530-12 (DEU-PERM-DS)","Lakewood, CO","[<nobr>$76,341 - $99,243 a year</nobr>]",False
28,CyberCoders,Data Scientist,"Boulder, CO",NaN,True
29,LENA Research Foundation,Sr. Research Engineer: Machine Learning and Co...,"Boulder, CO",NaN,True
...,...,...,...,...,...
1899,"RetailMeNot, Inc.",Sr. Data Scientist,"Austin, TX",NaN,True
1900,Sense Corp,Data Scientist,"Austin, TX",NaN,True
1901,MaxPoint,Senior Data Scientist - Econometrics,"Austin, TX 78759 (Arboretum area)",NaN,False
1902,NVIDIA,Research Scientist for Computer Vision / Machi...,"Austin, TX",NaN,False
1903,Alcatel-Lucent,Software Developer Co-op,"Austin, TX",NaN,False
1904,Ocean Conservancy,"Conservation Biologist, Gulf Restoration Program","Austin, TX 78701 (Downtown area)",NaN,False
1905,CDK Global,Business Security Officer,"Austin, TX",NaN,False
1906,Express Scripts,Senior Quantitative UX Researcher,"Austin, TX",NaN,False
1907,Signature Science,Bioinformatics Specialist,"Austin, TX",NaN,False
1908,The University of Texas System,Institutional Research Analyst,"Austin, TX","[<nobr>$4,459 a month</nobr>]",False
1909,Thermo Fisher Scientific,Application Scientist,"Austin, TX",NaN,False
1910,Emoters Robotics,Robotics software engineer (involves machine l...,"Austin, TX","[<nobr>$70,000 - $100,000 a year</nobr>]",False
1911,Indeed,Data Engineer,"Austin, TX",NaN,True
1912,Main Street Hub,Data Scientist,"Austin, TX",NaN,True
1913,Indeed,Data Scientist,"Austin, TX",NaN,True
1914,"RetailMeNot, Inc.",Sr. Data Scientist,"Austin, TX",NaN,True
1915,Sense Corp,Data Scientist,"Austin, TX",NaN,True
1916,"Gartner, Inc.","Content Marketing Analyst, Gartner Research","Austin, TX",NaN,False
1917,MaxPoint,Senior Data Scientist - Machine Learning,"Austin, TX 78759 (Arboretum area)",NaN,False
1918,The Jag Group,Senior Data Scientist - Machine Learning,"Austin, TX 73301 (St Edwards area)",NaN,False
1919,Natera,Clinical Data Reporter,"Austin, TX 78731",NaN,False
1920,"TEL Technology Center, America, Inc.",Scientist,"Austin, TX",NaN,False
1921,Zilliant,Senior Software Engineer – Science Team,"Austin, TX 78704 (South Lamar-South Congress a...",NaN,False
1922,Galvanize,"Associate Instructor, Data Scientist","Austin, TX",NaN,False
1923,Indeed,Data Scientist,"Austin, TX 78759 (Arboretum area)",NaN,False
1924,University of Texas at Austin,Engineering Scientist Associate - GNSS Analyst...,"Austin, TX","[<nobr>$5,400 - $6,500 a month</nobr>]",False
1925,HomeAway,Research Data Scientist,"Austin, TX 78704 (South Lamar-South Congress a...",NaN,False
1926,Indeed,Data Engineer,"Austin, TX",NaN,True
1927,Main Street Hub,Data Scientist,"Austin, TX",NaN,True
1928,Indeed,Data Scientist,"Austin, TX",NaN,True

In [7]:
#filter out sponsored

indeed = indeed.loc[indeed['Sponsored'] != True]
indeed = indeed.reset_index()
indeed

,index,Company,Job,Location,Salary,Sponsored
0,3,Navigant Consulting,Research Analyst,"Boulder, CO",NaN,False
1,4,cliexa,Data Scientist Intern,"Boulder, CO",NaN,False
2,5,University of Colorado,Professional Research Asst,"Boulder, CO",NaN,False
3,6,"Somalogic, Inc.",Bioinformatics Assoc. II/Sr. Assoc./Analyst/Sc...,"Boulder, CO 80301",NaN,False
4,7,Oracle,"Senior Product Manager - Measurement, Oracle D...","Broomfield, CO",NaN,False
5,8,Ibotta,Senior Data Scientist,"Denver, CO 80202 (Lodo area)",NaN,False
6,9,University of Colorado,Research Associate,"Boulder, CO",NaN,False
7,10,Deloitte,Big Data Senior Consultant,"Denver, CO 80203 (Capitol Hill area)",NaN,False
8,11,Deloitte,Big Data Manager,"Denver, CO 80203 (Capitol Hill area)",NaN,False
9,12,Planet Pharma,Statistical Programmer,"Denver, CO",NaN,False
10,18,Ball Aerospace,Administrative Associate II - National Defense...,"Broomfield, CO",NaN,False
11,19,"Corgenix, Inc",Postdoctoral Fellow - Assay Development,"Broomfield, CO 80020",NaN,False
12,20,UCAR,Engineer II,"Broomfield, CO",NaN,False
13,21,Specialty Chemicals,Research Scientist,"Denver, CO",NaN,False
14,22,IMM,Software Engineer ? Big Data,"Boulder, CO 80302",NaN,False
15,23,Archer,Software Engineer,"Boulder, CO",NaN,False
16,24,Southwest Research Institute,SR. RESEARCH SCIENTIST - HELIOPHYSICS,"Boulder, CO",NaN,False
17,25,OnDeck,Business Intelligence Analyst,"Denver, CO",NaN,False
18,26,Stanley Brothers Social Enterprises,Research and Development Scientist,"Boulder, CO 80301",NaN,False
19,27,Department Of The Interior,"Statistician, GS-1530-12 (DEU-PERM-DS)","Lakewood, CO","[<nobr>$76,341 - $99,243 a year</nobr>]",False
20,32,KPMG,Data Scientist / Machine Learning - Sr. Associate,"Denver, CO 80202 (Lodo area)",NaN,False
21,33,Galvanize,"Lead Instructor, Principal Data Scientist","Denver, CO",NaN,False
22,34,Layer3 TV,Research Analyst,"Denver, CO",NaN,False
23,35,AdTaxi Networks,Data Quality and Reporting Analyst,"Denver, CO",NaN,False
24,36,ArcherDX,Software Engineer,"Boulder, CO",NaN,False
25,37,"Toeroek Associates, Inc.",Environmental Research Analyst - Lakewood,"Lakewood, CO",NaN,False
26,38,"Muse Biotechnology, Inc.",Full Stack Developer,"Boulder, CO",NaN,False
27,39,Velocity Sciences,Research Associate I,"Boulder, CO 80301",NaN,False
28,40,Oracle,Sr. Data Scientist-TV,"Westminster, CO",NaN,False
29,41,Ball Aerospace,Material Property Specialist I (659107),"Broomfield, CO",NaN,False
...,...,...,...,...,...,...
1158,1886,KPMG,"Manager - Data Scientist, Big Data","Austin, TX 78701 (Downtown area)",NaN,False
1159,1887,Asuragen,Research Scientist,"Austin, TX",NaN,False
1160,1888,Spiceworks,"Director, Marketing Sciences & Advanced Analytics","Austin, TX",NaN,False
1161,1889,Infovision Consultants Inc,Senior Data Scientist,"Austin, TX 78716",NaN,False
1162,1890,Dimensional Fund Advisors,"Analyst, Research","Austin, TX",NaN,False
1163,1891,Texas Department of Public Safety,"Statistician III-IV, HSOC, THP-Austin","Austin, TX","[<nobr>$3,763 - $5,665 a month</nobr>]",False
1164,1892,Precision For Value,"Research Scientist, Advanced Modeling","Austin, TX",NaN,False
1165,1893,Clinical Pathology Laboratories,Quality Improvement Director,"Austin, TX",NaN,False
1166,1894,"Signature Science, LLC",Bioinformatics Specialist,"Austin, TX 78759 (Arboretum area)",NaN,False
1167,1895,"RetailMeNot, Inc.","Sr. Product Manager, Data","Austin, TX",NaN,False
1168,1901,MaxPoint,Senior Data Scientist - Econometrics,"Austin, TX 78759 (Arboretum area)",NaN,False
1169,1902,NVIDIA,Research Scientist for Computer Vision / Machi...,"Austin, TX",NaN,False
1170,1903,Alcatel-Lucent,Software Developer Co-op,"Austin, TX",NaN,False
1171,1904,Ocean Conservancy,"Conservation Biologist, Gulf Restoration Program","Austin, TX 78701 (Downtown area)",NaN,False
1172,1905,CDK Global,Business Security Officer,"Austin, TX",NaN,False
1173,1906,Express Scripts,Senior Quantitative UX Researcher,"Austin, TX",NaN,False
1174,1907,Signature Science,Bioinformatics Specialist,"Austin, TX",NaN,False
1175,1908,The University of Texas System,Institutional Research Analyst,"Austin, TX","[<nobr>$4,459 a month</nobr>]",False
1176,1909,Thermo Fisher Scientific,Application Scientist,"Austin, TX",NaN,False
1177,1910,Emoters Robotics,Robotics software engineer (involves machine l...,"Austin, TX","[<nobr>$70,000 - $100,000 a year</nobr>]",False
1178,1916,"Gartner, Inc.","Content Marketing Analyst, Gartner Research","Austin, TX",NaN,False
1179,1917,MaxPoint,Senior Data Scientist - Machine Learning,"Austin, TX 78759 (Arboretum area)",NaN,False
1180,1918,The Jag Group,Senior Data Scientist - Machine Learning,"Austin, TX 73301 (St Edwards area)",NaN,False
1181,1919,Natera,Clinical Data Reporter,"Austin, TX 78731",NaN,False
1182,1920,"TEL Technology Center, America, Inc.",Scientist,"Austin, TX",NaN,False
1183,1921,Zilliant,Senior Software Engineer – Science Team,"Austin, TX 78704 (South Lamar-South Congress a...",NaN,False
1184,1922,Galvanize,"Associate Instructor, Data Scientist","Austin, TX",NaN,False
1185,1923,Indeed,Data Scientist,"Austin, TX 78759 (Arboretum area)",NaN,False
1186,1924,University of Texas at Austin,Engineering Scientist Associate - GNSS Analyst...,"Austin, TX","[<nobr>$5,400 - $6,500 a month</nobr>]",False
1187,1925,HomeAway,Research Data Scientist,"Austin, TX 78704 (South Lamar-South Congress a...",NaN,False

In [8]:
indeed.drop(['index'], axis=1, inplace=True)
indeed

,Company,Job,Location,Salary,Sponsored
0,Navigant Consulting,Research Analyst,"Boulder, CO",NaN,False
1,cliexa,Data Scientist Intern,"Boulder, CO",NaN,False
2,University of Colorado,Professional Research Asst,"Boulder, CO",NaN,False
3,"Somalogic, Inc.",Bioinformatics Assoc. II/Sr. Assoc./Analyst/Sc...,"Boulder, CO 80301",NaN,False
4,Oracle,"Senior Product Manager - Measurement, Oracle D...","Broomfield, CO",NaN,False
5,Ibotta,Senior Data Scientist,"Denver, CO 80202 (Lodo area)",NaN,False
6,University of Colorado,Research Associate,"Boulder, CO",NaN,False
7,Deloitte,Big Data Senior Consultant,"Denver, CO 80203 (Capitol Hill area)",NaN,False
8,Deloitte,Big Data Manager,"Denver, CO 80203 (Capitol Hill area)",NaN,False
9,Planet Pharma,Statistical Programmer,"Denver, CO",NaN,False
10,Ball Aerospace,Administrative Associate II - National Defense...,"Broomfield, CO",NaN,False
11,"Corgenix, Inc",Postdoctoral Fellow - Assay Development,"Broomfield, CO 80020",NaN,False
12,UCAR,Engineer II,"Broomfield, CO",NaN,False
13,Specialty Chemicals,Research Scientist,"Denver, CO",NaN,False
14,IMM,Software Engineer ? Big Data,"Boulder, CO 80302",NaN,False
15,Archer,Software Engineer,"Boulder, CO",NaN,False
16,Southwest Research Institute,SR. RESEARCH SCIENTIST - HELIOPHYSICS,"Boulder, CO",NaN,False
17,OnDeck,Business Intelligence Analyst,"Denver, CO",NaN,False
18,Stanley Brothers Social Enterprises,Research and Development Scientist,"Boulder, CO 80301",NaN,False
19,Department Of The Interior,"Statistician, GS-1530-12 (DEU-PERM-DS)","Lakewood, CO","[<nobr>$76,341 - $99,243 a year</nobr>]",False
20,KPMG,Data Scientist / Machine Learning - Sr. Associate,"Denver, CO 80202 (Lodo area)",NaN,False
21,Galvanize,"Lead Instructor, Principal Data Scientist","Denver, CO",NaN,False
22,Layer3 TV,Research Analyst,"Denver, CO",NaN,False
23,AdTaxi Networks,Data Quality and Reporting Analyst,"Denver, CO",NaN,False
24,ArcherDX,Software Engineer,"Boulder, CO",NaN,False
25,"Toeroek Associates, Inc.",Environmental Research Analyst - Lakewood,"Lakewood, CO",NaN,False
26,"Muse Biotechnology, Inc.",Full Stack Developer,"Boulder, CO",NaN,False
27,Velocity Sciences,Research Associate I,"Boulder, CO 80301",NaN,False
28,Oracle,Sr. Data Scientist-TV,"Westminster, CO",NaN,False
29,Ball Aerospace,Material Property Specialist I (659107),"Broomfield, CO",NaN,False
...,...,...,...,...,...
1158,KPMG,"Manager - Data Scientist, Big Data","Austin, TX 78701 (Downtown area)",NaN,False
1159,Asuragen,Research Scientist,"Austin, TX",NaN,False
1160,Spiceworks,"Director, Marketing Sciences & Advanced Analytics","Austin, TX",NaN,False
1161,Infovision Consultants Inc,Senior Data Scientist,"Austin, TX 78716",NaN,False
1162,Dimensional Fund Advisors,"Analyst, Research","Austin, TX",NaN,False
1163,Texas Department of Public Safety,"Statistician III-IV, HSOC, THP-Austin","Austin, TX","[<nobr>$3,763 - $5,665 a month</nobr>]",False
1164,Precision For Value,"Research Scientist, Advanced Modeling","Austin, TX",NaN,False
1165,Clinical Pathology Laboratories,Quality Improvement Director,"Austin, TX",NaN,False
1166,"Signature Science, LLC",Bioinformatics Specialist,"Austin, TX 78759 (Arboretum area)",NaN,False
1167,"RetailMeNot, Inc.","Sr. Product Manager, Data","Austin, TX",NaN,False
1168,MaxPoint,Senior Data Scientist - Econometrics,"Austin, TX 78759 (Arboretum area)",NaN,False
1169,NVIDIA,Research Scientist for Computer Vision / Machi...,"Austin, TX",NaN,False
1170,Alcatel-Lucent,Software Developer Co-op,"Austin, TX",NaN,False
1171,Ocean Conservancy,"Conservation Biologist, Gulf Restoration Program","Austin, TX 78701 (Downtown area)",NaN,False
1172,CDK Global,Business Security Officer,"Austin, TX",NaN,False
1173,Express Scripts,Senior Quantitative UX Researcher,"Austin, TX",NaN,False
1174,Signature Science,Bioinformatics Specialist,"Austin, TX",NaN,False
1175,The University of Texas System,Institutional Research Analyst,"Austin, TX","[<nobr>$4,459 a month</nobr>]",False
1176,Thermo Fisher Scientific,Application Scientist,"Austin, TX",NaN,False
1177,Emoters Robotics,Robotics software engineer (involves machine l...,"Austin, TX","[<nobr>$70,000 - $100,000 a year</nobr>]",False
1178,"Gartner, Inc.","Content Marketing Analyst, Gartner Research","Austin, TX",NaN,False
1179,MaxPoint,Senior Data Scientist - Machine Learning,"Austin, TX 78759 (Arboretum area)",NaN,False
1180,The Jag Group,Senior Data Scientist - Machine Learning,"Austin, TX 73301 (St Edwards area)",NaN,False
1181,Natera,Clinical Data Reporter,"Austin, TX 78731",NaN,False
1182,"TEL Technology Center, America, Inc.",Scientist,"Austin, TX",NaN,False
1183,Zilliant,Senior Software Engineer – Science Team,"Austin, TX 78704 (South Lamar-South Congress a...",NaN,False
1184,Galvanize,"Associate Instructor, Data Scientist","Austin, TX",NaN,False
1185,Indeed,Data Scientist,"Austin, TX 78759 (Arboretum area)",NaN,False
1186,University of Texas at Austin,Engineering Scientist Associate - GNSS Analyst...,"Austin, TX","[<nobr>$5,400 - $6,500 a month</nobr>]",False
1187,HomeAway,Research Data Scientist,"Austin, TX 78704 (South Lamar-South Congress a...",NaN,False

In [9]:
#convert data types as needed

indeed['Job'].apply(lambda x: str(x))
indeed['Job'].apply(lambda x: type(x))

0       <type 'str'>
1       <type 'str'>
2       <type 'str'>
3       <type 'str'>
4       <type 'str'>
5       <type 'str'>
6       <type 'str'>
7       <type 'str'>
8       <type 'str'>
9       <type 'str'>
10      <type 'str'>
11      <type 'str'>
12      <type 'str'>
13      <type 'str'>
14      <type 'str'>
15      <type 'str'>
16      <type 'str'>
17      <type 'str'>
18      <type 'str'>
19      <type 'str'>
20      <type 'str'>
21      <type 'str'>
22      <type 'str'>
23      <type 'str'>
24      <type 'str'>
25      <type 'str'>
26      <type 'str'>
27      <type 'str'>
28      <type 'str'>
29      <type 'str'>
            ...
1158    <type 'str'>
1159    <type 'str'>
1160    <type 'str'>
1161    <type 'str'>
1162    <type 'str'>
1163    <type 'str'>
1164    <type 'str'>
1165    <type 'str'>
1166    <type 'str'>
1167    <type 'str'>
1168    <type 'str'>
1169    <type 'str'>
1170    <type 'str'>
1171    <type 'str'>
1172    <type 'str'>
1173    <type 'str'>
1174    <type 'str'>
1175    <type 'str'>
1176    <type 'str'>
1177    <type 'str'>
1178    <type 'str'>
1179    <type 'str'>
1180    <type 'str'>
1181    <type 'str'>
1182    <type 'str'>
1183    <type 'str'>
1184    <type 'str'>
1185    <type 'str'>
1186    <type 'str'>
1187    <type 'str'>
Name: Job, dtype: object

In [10]:
indeed['Location'].apply(lambda x: str(x))
indeed['Location'].apply(lambda x: type(x))

0       <type 'str'>
1       <type 'str'>
2       <type 'str'>
3       <type 'str'>
4       <type 'str'>
5       <type 'str'>
6       <type 'str'>
7       <type 'str'>
8       <type 'str'>
9       <type 'str'>
10      <type 'str'>
11      <type 'str'>
12      <type 'str'>
13      <type 'str'>
14      <type 'str'>
15      <type 'str'>
16      <type 'str'>
17      <type 'str'>
18      <type 'str'>
19      <type 'str'>
20      <type 'str'>
21      <type 'str'>
22      <type 'str'>
23      <type 'str'>
24      <type 'str'>
25      <type 'str'>
26      <type 'str'>
27      <type 'str'>
28      <type 'str'>
29      <type 'str'>
            ...
1158    <type 'str'>
1159    <type 'str'>
1160    <type 'str'>
1161    <type 'str'>
1162    <type 'str'>
1163    <type 'str'>
1164    <type 'str'>
1165    <type 'str'>
1166    <type 'str'>
1167    <type 'str'>
1168    <type 'str'>
1169    <type 'str'>
1170    <type 'str'>
1171    <type 'str'>
1172    <type 'str'>
1173    <type 'str'>
1174    <type 'str'>
1175    <type 'str'>
1176    <type 'str'>
1177    <type 'str'>
1178    <type 'str'>
1179    <type 'str'>
1180    <type 'str'>
1181    <type 'str'>
1182    <type 'str'>
1183    <type 'str'>
1184    <type 'str'>
1185    <type 'str'>
1186    <type 'str'>
1187    <type 'str'>
Name: Location, dtype: object

In [11]:
indeed['Salary'].apply(lambda x: str(x))
indeed['Salary'].apply(lambda x: type(x))

0       <type 'float'>
1       <type 'float'>
2       <type 'float'>
3       <type 'float'>
4       <type 'float'>
5       <type 'float'>
6       <type 'float'>
7       <type 'float'>
8       <type 'float'>
9       <type 'float'>
10      <type 'float'>
11      <type 'float'>
12      <type 'float'>
13      <type 'float'>
14      <type 'float'>
15      <type 'float'>
16      <type 'float'>
17      <type 'float'>
18      <type 'float'>
19        <type 'str'>
20      <type 'float'>
21      <type 'float'>
22      <type 'float'>
23      <type 'float'>
24      <type 'float'>
25      <type 'float'>
26      <type 'float'>
27      <type 'float'>
28      <type 'float'>
29      <type 'float'>
             ...
1158    <type 'float'>
1159    <type 'float'>
1160    <type 'float'>
1161    <type 'float'>
1162    <type 'float'>
1163      <type 'str'>
1164    <type 'float'>
1165    <type 'float'>
1166    <type 'float'>
1167    <type 'float'>
1168    <type 'float'>
1169    <type 'float'>
1170    <type 'float'>
1171    <type 'float'>
1172    <type 'float'>
1173    <type 'float'>
1174    <type 'float'>
1175      <type 'str'>
1176    <type 'float'>
1177      <type 'str'>
1178    <type 'float'>
1179    <type 'float'>
1180    <type 'float'>
1181    <type 'float'>
1182    <type 'float'>
1183    <type 'float'>
1184    <type 'float'>
1185    <type 'float'>
1186      <type 'str'>
1187    <type 'float'>
Name: Salary, dtype: object

In [12]:
#obtain salary values from current salary strings (step 1 of 2 for this task)
index = 0
for sal_string in indeed['Salary']:
    if type(sal_string) == float:
        pass
    else:
        m = re.search('\[\<nobr\>(.+?)\<\/nobr\>\]', sal_string)
        if m:
            sal_string = m.group(1)
            indeed['Salary'].iloc[index] = sal_string.replace("[<nobr>", "")
    index += 1
            
indeed

,Company,Job,Location,Salary,Sponsored
0,Navigant Consulting,Research Analyst,"Boulder, CO",NaN,False
1,cliexa,Data Scientist Intern,"Boulder, CO",NaN,False
2,University of Colorado,Professional Research Asst,"Boulder, CO",NaN,False
3,"Somalogic, Inc.",Bioinformatics Assoc. II/Sr. Assoc./Analyst/Sc...,"Boulder, CO 80301",NaN,False
4,Oracle,"Senior Product Manager - Measurement, Oracle D...","Broomfield, CO",NaN,False
5,Ibotta,Senior Data Scientist,"Denver, CO 80202 (Lodo area)",NaN,False
6,University of Colorado,Research Associate,"Boulder, CO",NaN,False
7,Deloitte,Big Data Senior Consultant,"Denver, CO 80203 (Capitol Hill area)",NaN,False
8,Deloitte,Big Data Manager,"Denver, CO 80203 (Capitol Hill area)",NaN,False
9,Planet Pharma,Statistical Programmer,"Denver, CO",NaN,False
10,Ball Aerospace,Administrative Associate II - National Defense...,"Broomfield, CO",NaN,False
11,"Corgenix, Inc",Postdoctoral Fellow - Assay Development,"Broomfield, CO 80020",NaN,False
12,UCAR,Engineer II,"Broomfield, CO",NaN,False
13,Specialty Chemicals,Research Scientist,"Denver, CO",NaN,False
14,IMM,Software Engineer ? Big Data,"Boulder, CO 80302",NaN,False
15,Archer,Software Engineer,"Boulder, CO",NaN,False
16,Southwest Research Institute,SR. RESEARCH SCIENTIST - HELIOPHYSICS,"Boulder, CO",NaN,False
17,OnDeck,Business Intelligence Analyst,"Denver, CO",NaN,False
18,Stanley Brothers Social Enterprises,Research and Development Scientist,"Boulder, CO 80301",NaN,False
19,Department Of The Interior,"Statistician, GS-1530-12 (DEU-PERM-DS)","Lakewood, CO","$76,341 - $99,243 a year",False
20,KPMG,Data Scientist / Machine Learning - Sr. Associate,"Denver, CO 80202 (Lodo area)",NaN,False
21,Galvanize,"Lead Instructor, Principal Data Scientist","Denver, CO",NaN,False
22,Layer3 TV,Research Analyst,"Denver, CO",NaN,False
23,AdTaxi Networks,Data Quality and Reporting Analyst,"Denver, CO",NaN,False
24,ArcherDX,Software Engineer,"Boulder, CO",NaN,False
25,"Toeroek Associates, Inc.",Environmental Research Analyst - Lakewood,"Lakewood, CO",NaN,False
26,"Muse Biotechnology, Inc.",Full Stack Developer,"Boulder, CO",NaN,False
27,Velocity Sciences,Research Associate I,"Boulder, CO 80301",NaN,False
28,Oracle,Sr. Data Scientist-TV,"Westminster, CO",NaN,False
29,Ball Aerospace,Material Property Specialist I (659107),"Broomfield, CO",NaN,False
...,...,...,...,...,...
1158,KPMG,"Manager - Data Scientist, Big Data","Austin, TX 78701 (Downtown area)",NaN,False
1159,Asuragen,Research Scientist,"Austin, TX",NaN,False
1160,Spiceworks,"Director, Marketing Sciences & Advanced Analytics","Austin, TX",NaN,False
1161,Infovision Consultants Inc,Senior Data Scientist,"Austin, TX 78716",NaN,False
1162,Dimensional Fund Advisors,"Analyst, Research","Austin, TX",NaN,False
1163,Texas Department of Public Safety,"Statistician III-IV, HSOC, THP-Austin","Austin, TX","$3,763 - $5,665 a month",False
1164,Precision For Value,"Research Scientist, Advanced Modeling","Austin, TX",NaN,False
1165,Clinical Pathology Laboratories,Quality Improvement Director,"Austin, TX",NaN,False
1166,"Signature Science, LLC",Bioinformatics Specialist,"Austin, TX 78759 (Arboretum area)",NaN,False
1167,"RetailMeNot, Inc.","Sr. Product Manager, Data","Austin, TX",NaN,False
1168,MaxPoint,Senior Data Scientist - Econometrics,"Austin, TX 78759 (Arboretum area)",NaN,False
1169,NVIDIA,Research Scientist for Computer Vision / Machi...,"Austin, TX",NaN,False
1170,Alcatel-Lucent,Software Developer Co-op,"Austin, TX",NaN,False
1171,Ocean Conservancy,"Conservation Biologist, Gulf Restoration Program","Austin, TX 78701 (Downtown area)",NaN,False
1172,CDK Global,Business Security Officer,"Austin, TX",NaN,False
1173,Express Scripts,Senior Quantitative UX Researcher,"Austin, TX",NaN,False
1174,Signature Science,Bioinformatics Specialist,"Austin, TX",NaN,False
1175,The University of Texas System,Institutional Research Analyst,"Austin, TX","$4,459 a month",False
1176,Thermo Fisher Scientific,Application Scientist,"Austin, TX",NaN,False
1177,Emoters Robotics,Robotics software engineer (involves machine l...,"Austin, TX","$70,000 - $100,000 a year",False
1178,"Gartner, Inc.","Content Marketing Analyst, Gartner Research","Austin, TX",NaN,False
1179,MaxPoint,Senior Data Scientist - Machine Learning,"Austin, TX 78759 (Arboretum area)",NaN,False
1180,The Jag Group,Senior Data Scientist - Machine Learning,"Austin, TX 73301 (St Edwards area)",NaN,False
1181,Natera,Clinical Data Reporter,"Austin, TX 78731",NaN,False
1182,"TEL Technology Center, America, Inc.",Scientist,"Austin, TX",NaN,False
1183,Zilliant,Senior Software Engineer – Science Team,"Austin, TX 78704 (South Lamar-South Congress a...",NaN,False
1184,Galvanize,"Associate Instructor, Data Scientist","Austin, TX",NaN,False
1185,Indeed,Data Scientist,"Austin, TX 78759 (Arboretum area)",NaN,False
1186,University of Texas at Austin,Engineering Scientist Associate - GNSS Analyst...,"Austin, TX","$5,400 - $6,500 a month",False
1187,HomeAway,Research Data Scientist,"Austin, TX 78704 (South Lamar-South Congress a...",NaN,False

In [13]:
#obtain salary values from current salary strings (step 2 of 2 for this task)

index = 0
for sal_string in indeed['Salary']:
    if type(sal_string) == float:
        pass
    else:
        num_list = re.findall("\d{2,3},\d{3}", sal_string)
        int_list = map(lambda x: int(x.replace(",", "")), num_list)
        if len(int_list) == 0:
            indeed['Salary'].iloc[index] = np.nan
        else:
            one_sal = sum(int_list)/len(int_list)
            indeed['Salary'].iloc[index] = one_sal            
    index += 1
    
indeed

,Company,Job,Location,Salary,Sponsored
0,Navigant Consulting,Research Analyst,"Boulder, CO",NaN,False
1,cliexa,Data Scientist Intern,"Boulder, CO",NaN,False
2,University of Colorado,Professional Research Asst,"Boulder, CO",NaN,False
3,"Somalogic, Inc.",Bioinformatics Assoc. II/Sr. Assoc./Analyst/Sc...,"Boulder, CO 80301",NaN,False
4,Oracle,"Senior Product Manager - Measurement, Oracle D...","Broomfield, CO",NaN,False
5,Ibotta,Senior Data Scientist,"Denver, CO 80202 (Lodo area)",NaN,False
6,University of Colorado,Research Associate,"Boulder, CO",NaN,False
7,Deloitte,Big Data Senior Consultant,"Denver, CO 80203 (Capitol Hill area)",NaN,False
8,Deloitte,Big Data Manager,"Denver, CO 80203 (Capitol Hill area)",NaN,False
9,Planet Pharma,Statistical Programmer,"Denver, CO",NaN,False
10,Ball Aerospace,Administrative Associate II - National Defense...,"Broomfield, CO",NaN,False
11,"Corgenix, Inc",Postdoctoral Fellow - Assay Development,"Broomfield, CO 80020",NaN,False
12,UCAR,Engineer II,"Broomfield, CO",NaN,False
13,Specialty Chemicals,Research Scientist,"Denver, CO",NaN,False
14,IMM,Software Engineer ? Big Data,"Boulder, CO 80302",NaN,False
15,Archer,Software Engineer,"Boulder, CO",NaN,False
16,Southwest Research Institute,SR. RESEARCH SCIENTIST - HELIOPHYSICS,"Boulder, CO",NaN,False
17,OnDeck,Business Intelligence Analyst,"Denver, CO",NaN,False
18,Stanley Brothers Social Enterprises,Research and Development Scientist,"Boulder, CO 80301",NaN,False
19,Department Of The Interior,"Statistician, GS-1530-12 (DEU-PERM-DS)","Lakewood, CO",87792,False
20,KPMG,Data Scientist / Machine Learning - Sr. Associate,"Denver, CO 80202 (Lodo area)",NaN,False
21,Galvanize,"Lead Instructor, Principal Data Scientist","Denver, CO",NaN,False
22,Layer3 TV,Research Analyst,"Denver, CO",NaN,False
23,AdTaxi Networks,Data Quality and Reporting Analyst,"Denver, CO",NaN,False
24,ArcherDX,Software Engineer,"Boulder, CO",NaN,False
25,"Toeroek Associates, Inc.",Environmental Research Analyst - Lakewood,"Lakewood, CO",NaN,False
26,"Muse Biotechnology, Inc.",Full Stack Developer,"Boulder, CO",NaN,False
27,Velocity Sciences,Research Associate I,"Boulder, CO 80301",NaN,False
28,Oracle,Sr. Data Scientist-TV,"Westminster, CO",NaN,False
29,Ball Aerospace,Material Property Specialist I (659107),"Broomfield, CO",NaN,False
...,...,...,...,...,...
1158,KPMG,"Manager - Data Scientist, Big Data","Austin, TX 78701 (Downtown area)",NaN,False
1159,Asuragen,Research Scientist,"Austin, TX",NaN,False
1160,Spiceworks,"Director, Marketing Sciences & Advanced Analytics","Austin, TX",NaN,False
1161,Infovision Consultants Inc,Senior Data Scientist,"Austin, TX 78716",NaN,False
1162,Dimensional Fund Advisors,"Analyst, Research","Austin, TX",NaN,False
1163,Texas Department of Public Safety,"Statistician III-IV, HSOC, THP-Austin","Austin, TX",NaN,False
1164,Precision For Value,"Research Scientist, Advanced Modeling","Austin, TX",NaN,False
1165,Clinical Pathology Laboratories,Quality Improvement Director,"Austin, TX",NaN,False
1166,"Signature Science, LLC",Bioinformatics Specialist,"Austin, TX 78759 (Arboretum area)",NaN,False
1167,"RetailMeNot, Inc.","Sr. Product Manager, Data","Austin, TX",NaN,False
1168,MaxPoint,Senior Data Scientist - Econometrics,"Austin, TX 78759 (Arboretum area)",NaN,False
1169,NVIDIA,Research Scientist for Computer Vision / Machi...,"Austin, TX",NaN,False
1170,Alcatel-Lucent,Software Developer Co-op,"Austin, TX",NaN,False
1171,Ocean Conservancy,"Conservation Biologist, Gulf Restoration Program","Austin, TX 78701 (Downtown area)",NaN,False
1172,CDK Global,Business Security Officer,"Austin, TX",NaN,False
1173,Express Scripts,Senior Quantitative UX Researcher,"Austin, TX",NaN,False
1174,Signature Science,Bioinformatics Specialist,"Austin, TX",NaN,False
1175,The University of Texas System,Institutional Research Analyst,"Austin, TX",NaN,False
1176,Thermo Fisher Scientific,Application Scientist,"Austin, TX",NaN,False
1177,Emoters Robotics,Robotics software engineer (involves machine l...,"Austin, TX",85000,False
1178,"Gartner, Inc.","Content Marketing Analyst, Gartner Research","Austin, TX",NaN,False
1179,MaxPoint,Senior Data Scientist - Machine Learning,"Austin, TX 78759 (Arboretum area)",NaN,False
1180,The Jag Group,Senior Data Scientist - Machine Learning,"Austin, TX 73301 (St Edwards area)",NaN,False
1181,Natera,Clinical Data Reporter,"Austin, TX 78731",NaN,False
1182,"TEL Technology Center, America, Inc.",Scientist,"Austin, TX",NaN,False
1183,Zilliant,Senior Software Engineer – Science Team,"Austin, TX 78704 (South Lamar-South Congress a...",NaN,False
1184,Galvanize,"Associate Instructor, Data Scientist","Austin, TX",NaN,False
1185,Indeed,Data Scientist,"Austin, TX 78759 (Arboretum area)",NaN,False
1186,University of Texas at Austin,Engineering Scientist Associate - GNSS Analyst...,"Austin, TX",NaN,False
1187,HomeAway,Research Data Scientist,"Austin, TX 78704 (South Lamar-South Congress a...",NaN,False

In [14]:
#making dummy variable for high/low salary (using salary median as defining value)

salary_median = indeed['Salary'].median()
print salary_median
indeed["Sal_Stat"] = ""
index = 0

for sal in indeed['Salary']:
    if np.isnan(sal):
        indeed['Sal_Stat'].iloc[index] = np.nan
    elif sal >= salary_median:
        indeed['Sal_Stat'].iloc[index] = 1
    else:
        indeed['Sal_Stat'].iloc[index] = 0
    index += 1
        
indeed

120000.0

,Company,Job,Location,Salary,Sponsored,Sal_Stat
0,Navigant Consulting,Research Analyst,"Boulder, CO",NaN,False,NaN
1,cliexa,Data Scientist Intern,"Boulder, CO",NaN,False,NaN
2,University of Colorado,Professional Research Asst,"Boulder, CO",NaN,False,NaN
3,"Somalogic, Inc.",Bioinformatics Assoc. II/Sr. Assoc./Analyst/Sc...,"Boulder, CO 80301",NaN,False,NaN
4,Oracle,"Senior Product Manager - Measurement, Oracle D...","Broomfield, CO",NaN,False,NaN
5,Ibotta,Senior Data Scientist,"Denver, CO 80202 (Lodo area)",NaN,False,NaN
6,University of Colorado,Research Associate,"Boulder, CO",NaN,False,NaN
7,Deloitte,Big Data Senior Consultant,"Denver, CO 80203 (Capitol Hill area)",NaN,False,NaN
8,Deloitte,Big Data Manager,"Denver, CO 80203 (Capitol Hill area)",NaN,False,NaN
9,Planet Pharma,Statistical Programmer,"Denver, CO",NaN,False,NaN
10,Ball Aerospace,Administrative Associate II - National Defense...,"Broomfield, CO",NaN,False,NaN
11,"Corgenix, Inc",Postdoctoral Fellow - Assay Development,"Broomfield, CO 80020",NaN,False,NaN
12,UCAR,Engineer II,"Broomfield, CO",NaN,False,NaN
13,Specialty Chemicals,Research Scientist,"Denver, CO",NaN,False,NaN
14,IMM,Software Engineer ? Big Data,"Boulder, CO 80302",NaN,False,NaN
15,Archer,Software Engineer,"Boulder, CO",NaN,False,NaN
16,Southwest Research Institute,SR. RESEARCH SCIENTIST - HELIOPHYSICS,"Boulder, CO",NaN,False,NaN
17,OnDeck,Business Intelligence Analyst,"Denver, CO",NaN,False,NaN
18,Stanley Brothers Social Enterprises,Research and Development Scientist,"Boulder, CO 80301",NaN,False,NaN
19,Department Of The Interior,"Statistician, GS-1530-12 (DEU-PERM-DS)","Lakewood, CO",87792,False,0
20,KPMG,Data Scientist / Machine Learning - Sr. Associate,"Denver, CO 80202 (Lodo area)",NaN,False,NaN
21,Galvanize,"Lead Instructor, Principal Data Scientist","Denver, CO",NaN,False,NaN
22,Layer3 TV,Research Analyst,"Denver, CO",NaN,False,NaN
23,AdTaxi Networks,Data Quality and Reporting Analyst,"Denver, CO",NaN,False,NaN
24,ArcherDX,Software Engineer,"Boulder, CO",NaN,False,NaN
25,"Toeroek Associates, Inc.",Environmental Research Analyst - Lakewood,"Lakewood, CO",NaN,False,NaN
26,"Muse Biotechnology, Inc.",Full Stack Developer,"Boulder, CO",NaN,False,NaN
27,Velocity Sciences,Research Associate I,"Boulder, CO 80301",NaN,False,NaN
28,Oracle,Sr. Data Scientist-TV,"Westminster, CO",NaN,False,NaN
29,Ball Aerospace,Material Property Specialist I (659107),"Broomfield, CO",NaN,False,NaN
...,...,...,...,...,...,...
1158,KPMG,"Manager - Data Scientist, Big Data","Austin, TX 78701 (Downtown area)",NaN,False,NaN
1159,Asuragen,Research Scientist,"Austin, TX",NaN,False,NaN
1160,Spiceworks,"Director, Marketing Sciences & Advanced Analytics","Austin, TX",NaN,False,NaN
1161,Infovision Consultants Inc,Senior Data Scientist,"Austin, TX 78716",NaN,False,NaN
1162,Dimensional Fund Advisors,"Analyst, Research","Austin, TX",NaN,False,NaN
1163,Texas Department of Public Safety,"Statistician III-IV, HSOC, THP-Austin","Austin, TX",NaN,False,NaN
1164,Precision For Value,"Research Scientist, Advanced Modeling","Austin, TX",NaN,False,NaN
1165,Clinical Pathology Laboratories,Quality Improvement Director,"Austin, TX",NaN,False,NaN
1166,"Signature Science, LLC",Bioinformatics Specialist,"Austin, TX 78759 (Arboretum area)",NaN,False,NaN
1167,"RetailMeNot, Inc.","Sr. Product Manager, Data","Austin, TX",NaN,False,NaN
1168,MaxPoint,Senior Data Scientist - Econometrics,"Austin, TX 78759 (Arboretum area)",NaN,False,NaN
1169,NVIDIA,Research Scientist for Computer Vision / Machi...,"Austin, TX",NaN,False,NaN
1170,Alcatel-Lucent,Software Developer Co-op,"Austin, TX",NaN,False,NaN
1171,Ocean Conservancy,"Conservation Biologist, Gulf Restoration Program","Austin, TX 78701 (Downtown area)",NaN,False,NaN
1172,CDK Global,Business Security Officer,"Austin, TX",NaN,False,NaN
1173,Express Scripts,Senior Quantitative UX Researcher,"Austin, TX",NaN,False,NaN
1174,Signature Science,Bioinformatics Specialist,"Austin, TX",NaN,False,NaN
1175,The University of Texas System,Institutional Research Analyst,"Austin, TX",NaN,False,NaN
1176,Thermo Fisher Scientific,Application Scientist,"Austin, TX",NaN,False,NaN
1177,Emoters Robotics,Robotics software engineer (involves machine l...,"Austin, TX",85000,False,0
1178,"Gartner, Inc.","Content Marketing Analyst, Gartner Research","Austin, TX",NaN,False,NaN
1179,MaxPoint,Senior Data Scientist - Machine Learning,"Austin, TX 78759 (Arboretum area)",NaN,False,NaN
1180,The Jag Group,Senior Data Scientist - Machine Learning,"Austin, TX 73301 (St Edwards area)",NaN,False,NaN
1181,Natera,Clinical Data Reporter,"Austin, TX 78731",NaN,False,NaN
1182,"TEL Technology Center, America, Inc.",Scientist,"Austin, TX",NaN,False,NaN
1183,Zilliant,Senior Software Engineer – Science Team,"Austin, TX 78704 (South Lamar-South Congress a...",NaN,False,NaN
1184,Galvanize,"Associate Instructor, Data Scientist","Austin, TX",NaN,False,NaN
1185,Indeed,Data Scientist,"Austin, TX 78759 (Arboretum area)",NaN,False,NaN
1186,University of Texas at Austin,Engineering Scientist Associate - GNSS Analyst...,"Austin, TX",NaN,False,NaN
1187,HomeAway,Research Data Scientist,"Austin, TX 78704 (South Lamar-South Congress a...",NaN,False,NaN

In [15]:
#based on output, I will have to eventually rebucket cities into regions in a state 
#(scraping scraped more cities than I intended, which will result in too many dummy variables)

indeed['Location'].value_counts()

Austin, TX                                      70
Las Vegas, NV                                   56
San Francisco, CA                               55
New York, NY                                    52
Denver, CO                                      50
Seattle, WA                                     50
Chicago, IL                                     49
Lehi, UT                                        46
Boston, MA                                      41
Fort Collins, CO                                36
Boulder, CO                                     27
Cambridge, MA                                   23
Burlington, NC                                  20
Mebane, NC                                      20
Fort Collins, CO 80526                          18
Broomfield, CO                                  16
Golden, CO                                      16
Sunnyvale, CA                                   16
Mountain View, CA                               15
Chicago, IL 60606 (Loop area)                   14
Westminster, CO                                 14
Draper, UT                                      12
Las Vegas, NV 89101 (Cultural Corridor area)    11
Bellevue, WA                                    10
Greensboro, NC 27401                            10
Chapel Hill, NC 27517                           10
Boulder, CO 80301                                9
Highland, UT                                     9
Las Vegas, NV 89113                              9
Lehi, UT 84005                                   9
                                                ..
San Jose, CA 95124 (Cambrian Park area)          1
New York, NY 10003 (Greenwich Village area)      1
Bellevue, WA 98004 (Downtown area)               1
Des Plaines, IL                                  1
San Mateo, CA 94404                              1
Skokie, IL 60077                                 1
Charlestown, MA 02129 (Fenway-Kenmore area)      1
Chicago, IL 60604 (Loop area)                    1
Centennial, CO 80111                             1
New York, NY 10018 (Clinton area)                1
San Mateo, CA 94402 (Beresford area)             1
Westmont, IL 60559                               1
Watertown, MA                                    1
Natick, MA                                       1
Greeley, CO                                      1
Cambridge, MA 02138 (West Cambridge area)        1
Oakland, CA                                      1
Lone Tree, CO 80124                              1
Chicago, IL 60613 (Uptown area)                  1
Nellis AFB, NV                                   1
New York, NY 10014 (West Village area)           1
New York, NY 10032 (Washington Heights area)     1
Wheat Ridge, CO 80033                            1
Renton, WA 98056                                 1
New York, NY 10154 (Midtown area)                1
Melrose Park, IL                                 1
Austin, TX 78716                                 1
New York, NY 10167 (Midtown area)                1
Pleasanton, CA 94588                             1
Boston, MA 02210 (South Boston area)             1
Name: Location, dtype: int64

In [16]:
#removing zipcode and neighborhood information from location values/strings

index = 0
for loc in indeed['Location']:
    loc_list = re.findall("[a-zA-Z ]+, [A-Z]{2}", loc)
    for ind_loc in loc_list:
        indeed['Location'].iloc[index] = ind_loc
    index += 1
    
indeed

,Company,Job,Location,Salary,Sponsored,Sal_Stat
0,Navigant Consulting,Research Analyst,"Boulder, CO",NaN,False,NaN
1,cliexa,Data Scientist Intern,"Boulder, CO",NaN,False,NaN
2,University of Colorado,Professional Research Asst,"Boulder, CO",NaN,False,NaN
3,"Somalogic, Inc.",Bioinformatics Assoc. II/Sr. Assoc./Analyst/Sc...,"Boulder, CO",NaN,False,NaN
4,Oracle,"Senior Product Manager - Measurement, Oracle D...","Broomfield, CO",NaN,False,NaN
5,Ibotta,Senior Data Scientist,"Denver, CO",NaN,False,NaN
6,University of Colorado,Research Associate,"Boulder, CO",NaN,False,NaN
7,Deloitte,Big Data Senior Consultant,"Denver, CO",NaN,False,NaN
8,Deloitte,Big Data Manager,"Denver, CO",NaN,False,NaN
9,Planet Pharma,Statistical Programmer,"Denver, CO",NaN,False,NaN
10,Ball Aerospace,Administrative Associate II - National Defense...,"Broomfield, CO",NaN,False,NaN
11,"Corgenix, Inc",Postdoctoral Fellow - Assay Development,"Broomfield, CO",NaN,False,NaN
12,UCAR,Engineer II,"Broomfield, CO",NaN,False,NaN
13,Specialty Chemicals,Research Scientist,"Denver, CO",NaN,False,NaN
14,IMM,Software Engineer ? Big Data,"Boulder, CO",NaN,False,NaN
15,Archer,Software Engineer,"Boulder, CO",NaN,False,NaN
16,Southwest Research Institute,SR. RESEARCH SCIENTIST - HELIOPHYSICS,"Boulder, CO",NaN,False,NaN
17,OnDeck,Business Intelligence Analyst,"Denver, CO",NaN,False,NaN
18,Stanley Brothers Social Enterprises,Research and Development Scientist,"Boulder, CO",NaN,False,NaN
19,Department Of The Interior,"Statistician, GS-1530-12 (DEU-PERM-DS)","Lakewood, CO",87792,False,0
20,KPMG,Data Scientist / Machine Learning - Sr. Associate,"Denver, CO",NaN,False,NaN
21,Galvanize,"Lead Instructor, Principal Data Scientist","Denver, CO",NaN,False,NaN
22,Layer3 TV,Research Analyst,"Denver, CO",NaN,False,NaN
23,AdTaxi Networks,Data Quality and Reporting Analyst,"Denver, CO",NaN,False,NaN
24,ArcherDX,Software Engineer,"Boulder, CO",NaN,False,NaN
25,"Toeroek Associates, Inc.",Environmental Research Analyst - Lakewood,"Lakewood, CO",NaN,False,NaN
26,"Muse Biotechnology, Inc.",Full Stack Developer,"Boulder, CO",NaN,False,NaN
27,Velocity Sciences,Research Associate I,"Boulder, CO",NaN,False,NaN
28,Oracle,Sr. Data Scientist-TV,"Westminster, CO",NaN,False,NaN
29,Ball Aerospace,Material Property Specialist I (659107),"Broomfield, CO",NaN,False,NaN
...,...,...,...,...,...,...
1158,KPMG,"Manager - Data Scientist, Big Data","Austin, TX",NaN,False,NaN
1159,Asuragen,Research Scientist,"Austin, TX",NaN,False,NaN
1160,Spiceworks,"Director, Marketing Sciences & Advanced Analytics","Austin, TX",NaN,False,NaN
1161,Infovision Consultants Inc,Senior Data Scientist,"Austin, TX",NaN,False,NaN
1162,Dimensional Fund Advisors,"Analyst, Research","Austin, TX",NaN,False,NaN
1163,Texas Department of Public Safety,"Statistician III-IV, HSOC, THP-Austin","Austin, TX",NaN,False,NaN
1164,Precision For Value,"Research Scientist, Advanced Modeling","Austin, TX",NaN,False,NaN
1165,Clinical Pathology Laboratories,Quality Improvement Director,"Austin, TX",NaN,False,NaN
1166,"Signature Science, LLC",Bioinformatics Specialist,"Austin, TX",NaN,False,NaN
1167,"RetailMeNot, Inc.","Sr. Product Manager, Data","Austin, TX",NaN,False,NaN
1168,MaxPoint,Senior Data Scientist - Econometrics,"Austin, TX",NaN,False,NaN
1169,NVIDIA,Research Scientist for Computer Vision / Machi...,"Austin, TX",NaN,False,NaN
1170,Alcatel-Lucent,Software Developer Co-op,"Austin, TX",NaN,False,NaN
1171,Ocean Conservancy,"Conservation Biologist, Gulf Restoration Program","Austin, TX",NaN,False,NaN
1172,CDK Global,Business Security Officer,"Austin, TX",NaN,False,NaN
1173,Express Scripts,Senior Quantitative UX Researcher,"Austin, TX",NaN,False,NaN
1174,Signature Science,Bioinformatics Specialist,"Austin, TX",NaN,False,NaN
1175,The University of Texas System,Institutional Research Analyst,"Austin, TX",NaN,False,NaN
1176,Thermo Fisher Scientific,Application Scientist,"Austin, TX",NaN,False,NaN
1177,Emoters Robotics,Robotics software engineer (involves machine l...,"Austin, TX",85000,False,0
1178,"Gartner, Inc.","Content Marketing Analyst, Gartner Research","Austin, TX",NaN,False,NaN
1179,MaxPoint,Senior Data Scientist - Machine Learning,"Austin, TX",NaN,False,NaN
1180,The Jag Group,Senior Data Scientist - Machine Learning,"Austin, TX",NaN,False,NaN
1181,Natera,Clinical Data Reporter,"Austin, TX",NaN,False,NaN
1182,"TEL Technology Center, America, Inc.",Scientist,"Austin, TX",NaN,False,NaN
1183,Zilliant,Senior Software Engineer – Science Team,"Austin, TX",NaN,False,NaN
1184,Galvanize,"Associate Instructor, Data Scientist","Austin, TX",NaN,False,NaN
1185,Indeed,Data Scientist,"Austin, TX",NaN,False,NaN
1186,University of Texas at Austin,Engineering Scientist Associate - GNSS Analyst...,"Austin, TX",NaN,False,NaN
1187,HomeAway,Research Data Scientist,"Austin, TX",NaN,False,NaN

In [17]:
indeed['Job'].value_counts()

Data Scientist                                                     50
Senior Data Scientist                                              45
Quantitative Analyst                                               23
Research Scientist                                                 22
Research Analyst                                                   17
Data Analyst                                                       15
Data Engineer                                                      11
Big Data Engineer                                                  11
Remote Principal Biostatistician                                   10
Head of Risk Contract Analytics                                    10
Medical Technician                                                 10
Study Director/Research Scientist                                  10
Associate Technical Director                                       10
Principal Data Scientist                                           10
Software Engineer - SDK                                             9
Applied Data Scientist                                              9
Technical Communication Specialist                                  9
Data Scientist - SAS                                                9
Machine Learning Engineer                                           9
Postdoctoral Fellow, Connecting Cloud Models to Observations        9
Senior Formulation Scientist (Dermatology)                          9
Statistical Retail Business Analyst / Data Scientist                9
Research Scientist/Scholar I, II, III (15-131) - OPEN POOL          9
Sr. Software Engineer - SDK                                         9
Formulation Scientist I                                             9
EPA Environmental Chemistry Laboratory Assistant, Chemical E...     9
Senior DevOps Engineer                                              9
EPA Environmental Chemistry Laboratory Assistant                    9
Research Scientist/Scholar I, II, III for CIRA in College Pa...     9
Data Scientist-Advanced Analytics                                   9
                                                                   ..
Senior Data Scientist - Geospatial Analytics                        1
Applied Research Scientist, Core Machine Learning                   1
Scientist II                                                        1
Entry Level Biostatistician                                         1
Quantitative Insights Analyst                                       1
Research Analyst (Products & Programs)                              1
Manager, Customer Analytics/Data Scientist                          1
Research Scientist, Epidemiology and Statistics, Health Anal...     1
BCA Analytics – Data Science Manager                                1
Scientist, Analytical Sciences                                      1
Scientist/Senior Scientist, Health R&D                              1
Enterprise Data Governance Analyst                                  1
Natural Language Research Scientist                                 1
Professional Research Assistant- Data Manager, Database Prog...     1
DATA ANALYST, GEOSPATIAL ANALYSIS                                   1
Business Data Analyst                                               1
Research Engineering/ Scientist Associate III - Lab Manager         1
Senior Bioinformatics Analyst                                       1
Director of Data Services - NEW YORK                                1
Instructor, Sr.Data Scientist                                       1
Full-Stack Developer                                                1
Research Analyst (Mixed Methods)                                    1
Fixed Income Research Analyst                                       1
Data Analyst - Cardiology                                           1
SENIOR DATA ANALYST                                                 1
Senior Prototype Machinist - 2nd Shift (659102)                     1
Senior Data Scientist - Econometrics                                1
Senior Data Scientist - Marketing Analytics                         1
Institutional Review Board Analyst - Research                       1
Data Science Intern                                                 1
Name: Job, dtype: int64

In [18]:
# Data Cleaning issues that will need to be addressed eventually: 
# if job title has two key words (e.g., senior and scientist) only first instance kept. As of now, any job title 
# with keywords lead, sr, senior will be bucketed as sr_type regardless of analyst and scientist keyword. Will probably
# need to make two seperate dummy variables: one for senior/manager titles, and one for actual job title (analyst, engineer, etc.)
# will have to address this later....

indeed['job_type'] = ""
index = 0

for job_string in indeed['Job']:
    if "Senior" in job_string:
        indeed['job_type'].iloc[index] = 'sr_type'
    elif "Sr" in job_string:
        indeed['job_type'].iloc[index] = 'sr_type'
    elif "Lead" in job_string:
        indeed['job_type'].iloc[index] = 'sr_type'
    elif "Analyst" in job_string:
        indeed['job_type'].iloc[index] = 'an_type'
    elif "Scientist" in job_string:
        indeed['job_type'].iloc[index] = 'sct_type'
    else:
        indeed['job_type'].iloc[index] = 'other'
    index += 1
        
indeed

,Company,Job,Location,Salary,Sponsored,Sal_Stat,job_type
0,Navigant Consulting,Research Analyst,"Boulder, CO",NaN,False,NaN,an_type
1,cliexa,Data Scientist Intern,"Boulder, CO",NaN,False,NaN,sct_type
2,University of Colorado,Professional Research Asst,"Boulder, CO",NaN,False,NaN,other
3,"Somalogic, Inc.",Bioinformatics Assoc. II/Sr. Assoc./Analyst/Sc...,"Boulder, CO",NaN,False,NaN,sr_type
4,Oracle,"Senior Product Manager - Measurement, Oracle D...","Broomfield, CO",NaN,False,NaN,sr_type
5,Ibotta,Senior Data Scientist,"Denver, CO",NaN,False,NaN,sr_type
6,University of Colorado,Research Associate,"Boulder, CO",NaN,False,NaN,other
7,Deloitte,Big Data Senior Consultant,"Denver, CO",NaN,False,NaN,sr_type
8,Deloitte,Big Data Manager,"Denver, CO",NaN,False,NaN,other
9,Planet Pharma,Statistical Programmer,"Denver, CO",NaN,False,NaN,other
10,Ball Aerospace,Administrative Associate II - National Defense...,"Broomfield, CO",NaN,False,NaN,other
11,"Corgenix, Inc",Postdoctoral Fellow - Assay Development,"Broomfield, CO",NaN,False,NaN,other
12,UCAR,Engineer II,"Broomfield, CO",NaN,False,NaN,other
13,Specialty Chemicals,Research Scientist,"Denver, CO",NaN,False,NaN,sct_type
14,IMM,Software Engineer ? Big Data,"Boulder, CO",NaN,False,NaN,other
15,Archer,Software Engineer,"Boulder, CO",NaN,False,NaN,other
16,Southwest Research Institute,SR. RESEARCH SCIENTIST - HELIOPHYSICS,"Boulder, CO",NaN,False,NaN,other
17,OnDeck,Business Intelligence Analyst,"Denver, CO",NaN,False,NaN,an_type
18,Stanley Brothers Social Enterprises,Research and Development Scientist,"Boulder, CO",NaN,False,NaN,sct_type
19,Department Of The Interior,"Statistician, GS-1530-12 (DEU-PERM-DS)","Lakewood, CO",87792,False,0,other
20,KPMG,Data Scientist / Machine Learning - Sr. Associate,"Denver, CO",NaN,False,NaN,sr_type
21,Galvanize,"Lead Instructor, Principal Data Scientist","Denver, CO",NaN,False,NaN,sr_type
22,Layer3 TV,Research Analyst,"Denver, CO",NaN,False,NaN,an_type
23,AdTaxi Networks,Data Quality and Reporting Analyst,"Denver, CO",NaN,False,NaN,an_type
24,ArcherDX,Software Engineer,"Boulder, CO",NaN,False,NaN,other
25,"Toeroek Associates, Inc.",Environmental Research Analyst - Lakewood,"Lakewood, CO",NaN,False,NaN,an_type
26,"Muse Biotechnology, Inc.",Full Stack Developer,"Boulder, CO",NaN,False,NaN,other
27,Velocity Sciences,Research Associate I,"Boulder, CO",NaN,False,NaN,other
28,Oracle,Sr. Data Scientist-TV,"Westminster, CO",NaN,False,NaN,sr_type
29,Ball Aerospace,Material Property Specialist I (659107),"Broomfield, CO",NaN,False,NaN,other
...,...,...,...,...,...,...,...
1158,KPMG,"Manager - Data Scientist, Big Data","Austin, TX",NaN,False,NaN,sct_type
1159,Asuragen,Research Scientist,"Austin, TX",NaN,False,NaN,sct_type
1160,Spiceworks,"Director, Marketing Sciences & Advanced Analytics","Austin, TX",NaN,False,NaN,other
1161,Infovision Consultants Inc,Senior Data Scientist,"Austin, TX",NaN,False,NaN,sr_type
1162,Dimensional Fund Advisors,"Analyst, Research","Austin, TX",NaN,False,NaN,an_type
1163,Texas Department of Public Safety,"Statistician III-IV, HSOC, THP-Austin","Austin, TX",NaN,False,NaN,other
1164,Precision For Value,"Research Scientist, Advanced Modeling","Austin, TX",NaN,False,NaN,sct_type
1165,Clinical Pathology Laboratories,Quality Improvement Director,"Austin, TX",NaN,False,NaN,other
1166,"Signature Science, LLC",Bioinformatics Specialist,"Austin, TX",NaN,False,NaN,other
1167,"RetailMeNot, Inc.","Sr. Product Manager, Data","Austin, TX",NaN,False,NaN,sr_type
1168,MaxPoint,Senior Data Scientist - Econometrics,"Austin, TX",NaN,False,NaN,sr_type
1169,NVIDIA,Research Scientist for Computer Vision / Machi...,"Austin, TX",NaN,False,NaN,sct_type
1170,Alcatel-Lucent,Software Developer Co-op,"Austin, TX",NaN,False,NaN,other
1171,Ocean Conservancy,"Conservation Biologist, Gulf Restoration Program","Austin, TX",NaN,False,NaN,other
1172,CDK Global,Business Security Officer,"Austin, TX",NaN,False,NaN,other
1173,Express Scripts,Senior Quantitative UX Researcher,"Austin, TX",NaN,False,NaN,sr_type
1174,Signature Science,Bioinformatics Specialist,"Austin, TX",NaN,False,NaN,other
1175,The University of Texas System,Institutional Research Analyst,"Austin, TX",NaN,False,NaN,an_type
1176,Thermo Fisher Scientific,Application Scientist,"Austin, TX",NaN,False,NaN,sct_type
1177,Emoters Robotics,Robotics software engineer (involves machine l...,"Austin, TX",85000,False,0,other
1178,"Gartner, Inc.","Content Marketing Analyst, Gartner Research","Austin, TX",NaN,False,NaN,an_type
1179,MaxPoint,Senior Data Scientist - Machine Learning,"Austin, TX",NaN,False,NaN,sr_type
1180,The Jag Group,Senior Data Scientist - Machine Learning,"Austin, TX",NaN,False,NaN,sr_type
1181,Natera,Clinical Data Reporter,"Austin, TX",NaN,False,NaN,other
1182,"TEL Technology Center, America, Inc.",Scientist,"Austin, TX",NaN,False,NaN,sct_type
1183,Zilliant,Senior Software Engineer – Science Team,"Austin, TX",NaN,False,NaN,sr_type
1184,Galvanize,"Associate Instructor, Data Scientist","Austin, TX",NaN,False,NaN,sct_type
1185,Indeed,Data Scientist,"Austin, TX",NaN,False,NaN,sct_type
1186,University of Texas at Austin,Engineering Scientist Associate - GNSS Analyst...,"Austin, TX",NaN,False,NaN,an_type
1187,HomeAway,Research Data Scientist,"Austin, TX",NaN,False,NaN,sct_type

In [19]:
# drop rows with NaN salary values 

indeed = indeed.dropna()
indeed.head()

,Company,Job,Location,Salary,Sponsored,Sal_Stat,job_type
19,Department Of The Interior,"Statistician, GS-1530-12 (DEU-PERM-DS)","Lakewood, CO",87792,False,0,other
36,Mental Health Center of Denver,Financial Data Scientist,"Denver, CO",75000,False,0,sct_type
99,Denver Public Schools,SENIOR RESEARCH ANALYST,"Denver, CO",68983,False,0,other
105,Workbridge Associates,Mid-Level Data Scientist,"Chicago, IL",105000,False,0,sct_type
110,Workbridge Associates,Data Scientist,"Chicago, IL",95000,False,0,sct_type

In [20]:
#save as CSV

indeed.to_csv('indeed.csv')